trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  IMAGE_NAME: '$(dockerHubUserName)/publish-teacher-training'

steps:
- script: |
    set -x
    GIT_SHORT_SHA=$(echo $(Build.SourceVersion) | cut -c 1-7)
    IMAGE_NAME_WITH_TAG=$(IMAGE_NAME):$GIT_SHORT_SHA
    set +x
    echo "##vso[build.updatebuildnumber]$GIT_SHORT_SHA"
    echo "##vso[task.setvariable variable=IMAGE_NAME_WITH_TAG;]$IMAGE_NAME_WITH_TAG"
    echo '$(System.PullRequest.SourceBranch)'> $(build.artifactstagingdirectory)/prbranch.info
    echo $(Build.SourceVersion) > COMMIT_SHA
  displayName: 'Set version number'

- script: docker pull $(IMAGE_NAME):latest || true
  displayName: "Pull latest docker image to cache"

- task: Docker@1
  displayName: Build image
  inputs:
    command: Build an image
    imageName: $(IMAGE_NAME)
    dockerFile: Dockerfile
    arguments: '--cache-from $(IMAGE_NAME):latest'
    addDefaultLabels: false

- task: Docker@1
  displayName: Run ruby linter
  inputs:
    command: Run an image
    imageName: $(IMAGE_NAME)
    containerCommand: rubocop app config lib spec --format clang
    runInBackground: false

- task: Docker@1
  displayName: Run sass linter
  inputs:
    command: Run an image
    imageName: $(IMAGE_NAME)
    containerCommand: scss-lint app/webpacker/stylesheets
    runInBackground: false

- script: |
    set -x
    docker run --name test-run-image -d $(IMAGE_NAME)
    docker exec test-run-image rake "parallel:spec[,, -O .azure_parallel]"
    test_result=$?

    docker cp test-run-image:/app/rspec-output .
    docker cp test-run-image:/app/coverage .

    docker stop test-run-image
    docker rm test-run-image

    exit $test_result
  displayName: 'Run ruby tests'

- bash: |
    set -x
    # Start up container and run the ruby test suite
    docker run --name test-run-image -d $(IMAGE_NAME)
    docker exec test-run-image yarn test --coverage
    test_result=$?

    # Copy test results and coverage to docker host (used by another script)
    docker cp test-run-image:/app/coverage .

    # Remove container
    docker rm -f test-run-image

    exit $test_result
  displayName: 'Run JavaScript tests'

- task: Docker@1
  displayName: Run Brakeman static analysis
  inputs:
    command: Run an image
    imageName: $(IMAGE_NAME)
    containerCommand: rails brakeman
    runInBackground: false

- script: |
    set -x
    curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    chmod +x ./cc-test-reporter

    ./cc-test-reporter before-build
    # As the tests were run in the docker container the paths to the coverage are prefixed with "/app/"
    # So we need to replace it with the docker hosts current directory
    sed "s|\"/app/|\"`pwd`/|g" coverage/.resultset.json -i

    # Format the two different test coverage formats (SimpleCov anf lcov) to code climates json format
    ./cc-test-reporter format-coverage --input-type simplecov --output coverage/rspec.json
    ./cc-test-reporter format-coverage --input-type lcov --output coverage/javascript.json

    # Aggregate the two results to form a single result for our code base
    ./cc-test-reporter sum-coverage --output 'coverage/total.json' coverage/javascript.json coverage/rspec.json

    # Upload the our test coverage to code climat
    ./cc-test-reporter upload-coverage --input coverage/total.json


    export SONAR_SCANNER_VERSION=4.2.0.1873
    export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
    curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
    unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
    export PATH=$SONAR_SCANNER_HOME/bin:$PATH
    export SONAR_SCANNER_OPTS="-server"

    sonar-scanner \
      -Dsonar.organization=dfe-digital \
      -Dsonar.projectKey=DFE-Digital_publish-teacher-training \
      -Dsonar.sources=. \
      -Dsonar.host.url=https://sonarcloud.io \
      -Dsonar.login=cfe8b8ccdb31562c5587b80a5bc3ae16b9814af2

  displayName: 'Publish Code Climate Test Coverage'
  env:
    CC_TEST_REPORTER_ID: $(ccReporterID)
    GIT_BRANCH: $(Build.SourceBranchName)

- task: Docker@1
  displayName: Tag image with current build number $(Build.BuildNumber)
  inputs:
    command: Tag image
    imageName: $(IMAGE_NAME)
    arguments: $(IMAGE_NAME_WITH_TAG)

- task: Docker@1
  displayName: Docker Hub login
  inputs:
    command: login
    containerregistrytype: Container Registry
    dockerRegistryEndpoint: DfE Docker Hub

- task: Docker@1
  displayName: Push tagged image
  inputs:
    command: Push an image
    imageName: $(IMAGE_NAME_WITH_TAG)

- task: Docker@1
  displayName: Push tagged image (latest) if master
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    command: Push an image
    imageName: '$(IMAGE_NAME):latest'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    Contents: |
     azure/**
     end-to-end-tests/**
    TargetFolder: '$(build.artifactstagingdirectory)'
    OverWrite: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: 'rspec-output/*.xml'
    failedTaskOnFailedTest: true
