dfe_signin:
  # Our service name
  identifier: bats2
  # URL that the users are redirected to for signing in
  issuer: https://test-oidc.signin.education.gov.uk/
  # URL of the users profile
  profile: https://test-profile.signin.education.gov.uk
  # This value must be set otherwise sign in will fail
  secret: foobar
  # URL of this app for the callback after sigining in
  base_url: https://localhost:3000
  # The URL support users are directed to in order to find a user by email
  user_search_url: https://test-support.signin.education.gov.uk/users
manage_backend:
  algorithm: HS256
  # Set this in the env! The below ensures that we are un-authenticatable if we
  # forget to do this in production.
  secret: <%= SecureRandom.base64 %>
  # URL of the API app (teacher-training-api)
  base_url: http://localhost:3001
search_ui:
  # URL of the C# search ui app (search-and-compare-ui)
  base_url: https://localhost:5000
notify:
  service_url: https://www.notifications.service.gov.uk/services/022acc23-c40a-4077-bbd6-fc98b2155534
  unregistered_user_template_url: https://www.notifications.service.gov.uk/services/022acc23-c40a-4077-bbd6-fc98b2155534/templates/9ecac443-8cfd-49ac-ac59-e7ffa0ab6278
  registered_user_template_url: https://www.notifications.service.gov.uk/services/022acc23-c40a-4077-bbd6-fc98b2155534/templates/4da327dd-907a-4619-abe6-45f348bb2fa3
google_forms:
  next_cycle:
    new_course_for_accredited_bodies:
      url: https://docs.google.com/forms/d/e/1FAIpQLScckkzOwt93FTZGgZCBRA6spAnSO06UKewD5N6P3moBhIpKiA/viewform?usp=pp_url
      email_entry: entry.957076544
      provider_code_entry: entry.1735563938
    new_course_for_unaccredited_bodies:
      url: https://docs.google.com/forms/d/e/1FAIpQLSeD1BwS11lYm4PJ8WZMRIU5U02h0z-T5WlC0aqycc1CHV-e0A/viewform?usp=pp_url
      email_entry: entry.1033530353
      provider_code_entry: entry.158771972
  current_cycle:
    new_course_for_accredited_bodies:
      url: https://docs.google.com/forms/d/e/1FAIpQLScckkzOwt93FTZGgZCBRA6spAnSO06UKewD5N6P3moBhIpKiA/viewform?usp=pp_url
      email_entry: entry.957076544
      provider_code_entry: entry.1735563938
    new_course_for_unaccredited_bodies:
      url: https://docs.google.com/forms/d/e/1FAIpQLSeD1BwS11lYm4PJ8WZMRIU5U02h0z-T5WlC0aqycc1CHV-e0A/viewform?usp=pp_url
      email_entry: entry.1033530353
      provider_code_entry: entry.158771972
service_support:
  contact_email_address: becomingateacher@digital.education.gov.uk
environment:
  label: "Beta"
  selector_name: "beta"
current_cycle: 2020
application_name: publish-teacher-training
logstash:
  type: tcp
  host: # Our hostname here
  port: # Our port here
  ssl_enable: true
log_level: info
google:
  maps_api_key: replace_me
use_ssl: true
features:
  signin_intercept: false
  signin_by_email: false
  dfe_signin: true
  rollover:
    # During rollover providers should be able to edit current & next recruitment cycle courses
    can_edit_current_and_next_cycles: true
    # Normally a short period of time between rollover and the next cycle
    # actually starting when it would be set to false
    has_current_cycle_started?: true
commit_sha_file: COMMIT_SHA
allocations_state: closed
basic_auth: false
developer_auth: false
