dfe_signin:
  # Our service name
  identifier: bats2
  # URL that the users are redirected to for signing in
  issuer: https://signin-test-oidc-as.azurewebsites.net
  # URL of the users profile
  profile: https://signin-test-pfl-as.azurewebsites.net
  # This value must be set otherwise sign in will fail
  secret: foobar
  # URL of this app for the callback after sigining in
  base_url: https://localhost:3000
manage_backend:
  algorithm: HS256
  # Set this in the env! The below ensures that we are un-authenticatable if we
  # forget to do this in production.
  secret: <%= SecureRandom.base64 %>
  # URL of the API app (manage-courses-backend)
  base_url: http://localhost:3001
search_ui:
  # URL of the C# search ui app (search-and-compare-ui)
  base_url: https://localhost:5000
google_forms:
  current_cycle:
    new_course_for_accredited_bodies:
      url: https://docs.google.com/forms/d/e/1FAIpQLSd4k5wSjrVyFu-FW4ZaSsrbK0AwTpjmzfyTdfa_qdXLZ313HQ/viewform?usp=pp_url
      email_entry: entry.957076544
      provider_code_entry: entry.1735563938
    new_course_for_unaccredited_bodies:
      url: https://docs.google.com/forms/d/e/1FAIpQLSeatJO2ZuqM-fnRJxEo6IIF0hZIU63JGnx0sDXO6Ulax7U_bA/viewform?usp=pp_url
      email_entry: entry.1033530353
      provider_code_entry: entry.158771972
  next_cycle:
    new_course_for_accredited_bodies:
      url: https://docs.google.com/forms/d/e/1FAIpQLScckkzOwt93FTZGgZCBRA6spAnSO06UKewD5N6P3moBhIpKiA/viewform?usp=pp_url
      email_entry: entry.957076544
      provider_code_entry: entry.1735563938
    new_course_for_unaccredited_bodies:
      url: https://docs.google.com/forms/d/e/1FAIpQLSeD1BwS11lYm4PJ8WZMRIU5U02h0z-T5WlC0aqycc1CHV-e0A/viewform?usp=pp_url
      email_entry: entry.1033530353
      provider_code_entry: entry.158771972
service_support:
  contact_email_address: becomingateacher@digital.education.gov.uk
environment:
  label: "Beta"
  selector_name: "beta"
rollover: false
current_cycle: 2020
