dfe_signin:
  secret: please_change_me # Override with SETTINGS__DFE_SIGNIN__SECRET
  base_url: https://localhost:3000
manage_backend:
  secret: secret
  base_url: http://localhost:3001
search_ui:
  base_url: https://localhost:5000
environment:
  label: "Development"
  selector_name: "development"
log_level: debug
use_ssl: false
allocations_state: closed
